#!/usr/bin/env php
<?php

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;
use Dotenv\Dotenv;
use Psr\Container\ContainerInterface;

require_once __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv::createImmutable(__DIR__.'/');
$dotenv->load();

/** @var ContainerInterface */
$container = require_once __DIR__ . '/src/config/container.php';

ConsoleRunner::run(new SingleManagerProvider($container->get(EntityManager::class)));
